= Malcom X
Mathias Bal

== Wer ist Malcom X?

=== Frühe Kindheit
* geb. Malcom Little in Nebraska
* Sohn eines Bürgerrechtsaktivist (& Priester)
* sein Vater wurde vom KKK gekidnapped als seine Mutter noch mit ihm schwanger war
und an ein Bahngleis gebunden

=== Späten Jugendjahren
* mit 13 Schule abgebrochen
* ins Gefängnis gewandert für 10 Jahre
** im Gefängnis lerne er über die "Nation Of Islam", da diese Afroamerikaner annahmen und ein Zufluchtsort vor Weißen war

=== Nation of Islam
Die NOI strebt an das soziale und wirtschaftliche Umfeld der Afroamerikaner zu stärken
und gleichzeitig traditionelle islamische Werte beizubehalten

=== Erwachsenenalter
* Nach dem Gefängnis lehnte er seinen Sklavennamen ab und bekam Malcom X
* In den 50igern und 60igern war er der Pressesprecher von NOI

== Die Bewegung
=== Gewalttätige Wege
* Gewalt wirksamer ist als Gewaltlosigkeit
** Aufforderung auf gewaltsamer Weise gegen die weißen Amerikaner zu protestieren
* Kritisierte Martin Luther King Jr.


== Das Ende
=== Ermordung von Malcom X

* Ins Visier nach der NOI
** Bomben in seinem Auto und in seinem Haus
* Malcolm wurde in Harlem, New York 15x von einem Anhänger der NOI in die Brust gestochen
